### ISSUE TITLE
반갑습니다

### ISSUE THREAD

**Issue by jinacamy** [morecool/transportfever2_kr#11]
오늘도 게임하면서 어색한 부분을 검수중입니다. 

한분 더 추가되서 이번에 트램이 노면전차로 바뀐거 같네요. 

한국말로 맞는 말이긴 하네요. 그래서 이번에 통일을 하자해서 글을 씁니다.

비행기 > 항공기
배 > 선박

여러분 생각은 어떠신지요

**Comment by morecool** [comment]
네 관련내용 정리해서 파일로 올리도록 하겠습니다.

**Comment by morecool** [comment]
RULE.md 파일 참조하시기 바랍니다.
감사합니다.
