### ISSUE TITLE
res 번역 오류

### ISSUE THREAD

**Issue by UCirce** [morecool/transportfever2_kr#13]
res 번역중에
MISSION_STARFLIGHT_TASK_HELLPILOT_PLANES_TASK 
이쪽 부분 번역 오류 있습니다
영어 원본에 없는 [link=jump_airfield] 부분이 추가가 되어서 
캠페인 챕터2 4번째 미션 불러오고나서 튕깁니다

**Comment by morecool** [comment]
해당 부분 및 동일 오류 발생 부분 수정하였습니다.
