### ISSUE TITLE
res 태그 오류

### ISSUE THREAD

**Issue by UCirce** [morecool/transportfever2_kr#18]
MISSION_STARFLIGHT_TASK_PREMIERE_ORGANIZE_TASK
and the [link=jump_premiere]premier[/link]. 번역 누락

MISSION_STARFLIGHT_TASK_PLANES_TASKS_TASK
and the [link=jump_sawmill]saw mill[/link]. 번역 누락

MISSION_STARFLIGHT_TASK_TYCOON_STOCK_TASK
[link=jump_golfcourse골프코스[/link][link=jump_party]파티장 
 ] 빠져있음
영어 원본:[link=jump_golfcourse]

MISSION_SILVERCITY_MEDAL_PONDEROSA_DELIVER_TASK
영어 원본: [link=jump_woodProcessingMill]timber supply
번역:[link=jump_woodProcessing Mill]팀버 서플라이
Processing 과 Mill 사이에 띄어쓰기 있음

오류 찾았습니다 확인 후 수정하시면 될 것 같네요

**Comment by morecool** [comment]
수정 반영했습니다. 감사합니다.
