### ISSUE TITLE
챕터1-5시베리아 철도

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [morecool/transportfever2_kr#19]
캠페인 챕터1 시베리아 철도에서 맨 처음 미션 나레이션 나오고서 계속 누르면 팅겨버리는 버그가 있네요

게임 자체 버그인가 확인해봤는데 영어는 문제 없이 다음 화면으로 넘어갑니다
나중에 시간되실때 확인 부탁드립니다

번역에 수고 많으십니다 감사합니다
챕터1-3에서 양미션에서 물음표 안뜨는문제도 있긴했는데
이건 게임내 버그같아서 따로 해결해보려고 합니다

**Comment by lov2plus** [comment]
저도 그러네요.

**Comment by morecool** [comment]
어제 해당 부분 수정했는데 다시 받아서 해도 마찬가지인가요?

**Comment by lov2plus** [comment]
> 어제 해당 부분 수정했는데 다시 받아서 해도 마찬가지인가요?

네  17일자 받아서 했는데도 그러더라고요

**Comment by morecool** [comment]
새버전으로는 아무리 해봐도 오류 안나고 정상적으로 플레이 되는데요..
파일을 잘못 받으셨거나 해당 폴더에 이름 안바꾸고 넣으신게 아닌가 싶네요.

**Comment by morecool** [comment]
![20191218120116_1](https://user-images.githubusercontent.com/9711761/71052425-9fe6d800-218e-11ea-9278-572fd60315fc.jpg)

**Comment by Twotoolus-FLY-LShst** [comment]
@morecool 
새로 업로드하신 파일로 변경하였고 잘 로딩됩니다
감사합니다.

**Comment by lov2plus** [comment]
18일자 수정버전으로 잘됩니다.
감사합니다.
