### ISSUE TITLE
미션 1 - 7(맨마지막거) 번역 누락(보너스 작업 술탄 풀먼 차량 > 티세트 발견)

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [morecool/transportfever2_kr#20]
보너스 작업
술탄 풀먼 차량 > 티세트 발견
번역 안된 문구 있음

물론 미션 진행하는데는 아무 지장 없습니다
ㅇㅁ< b

급한사항은 아니니 나중에 시간되실때 같이 작업해주시면 될 것 같습니다
감사합니다
![05465456](https://user-images.githubusercontent.com/23209374/71053807-0968e580-2193-11ea-86d5-8d37360f7711.png)

**Comment by morecool** [comment]
해당 내용 수정 반영하였습니다. 감사합니다.
