### ISSUE TITLE
Version 27560 (December 19) 업데이트 이후 한글 반영 안되는 현상

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [morecool/transportfever2_kr#21]
Version 27560 (December 19) 업데이트 이후
acf 파일 koreana로 되어 있고
업데이트 된 이후 res와 base 파일을 교체하여도 영어로 보이는 현상 있음

**Comment by morecool** [comment]
koreana 설정을 제작사 쪽에서 삭제한것 같습니다.
일본어 설정방식으로 하시면 됩니다. 자세한 사항은 README에 업데이트 했습니다.
