### ISSUE TITLE
캠페인 2-4(야심가) 번역 오류

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [morecool/transportfever2_kr#22]
캠페인 2-4(야심가) 게임 내 자체 문구 오류입니다

보너스 작업 > 청문에 대한 비행편에
비행기를 구매하고 워싱턴으로 항공여행을 선물합시다가 아닌
비행기를 판매하여 워싱턴으로 비행기를 보냅시다로 수정 부탁드립니다

비행기를 거의 대부분 판매하니 미션이 깨지는것을 확인했고
이 현상에 대한 토론에 대한 버그(문구 에러) 언급 글이 있습니다

참조글
https://steamcommunity.com/app/1066780/discussions/0/3963662399212543681/

![번역 오류](https://user-images.githubusercontent.com/23209374/71240890-98b9f880-234d-11ea-8964-73743ffe6406.png)

**Comment by morecool** [comment]
해당내용 수정 적용했습니다.

감사합니다.
