### ISSUE TITLE
!!!!! 캠페인 미션 3-4 해방된 시장 도시 지명 문제(미션 진행에 매우 중요함)

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [morecool/transportfever2_kr#23]
캠페인 미션 3-4 해방된 시장 도시 지명 문제

캠페인 진행중
지역화 > 계약을 쟁취하다에서
영어로 BW인 바덴 뷔르탬베르크, BY인 바바리아 선택이 나옵니다

문제는 도시 뒤에 (BW) (BY)가 표시되어 있어야되는데
전부 괄호 없이 도시명이 번역되어버리는 바람에 미션이 불가능 합니다

이미 클리어한 유튜버가 있어서 해당 도시명 변경이 가능한지는 모르겠지만
적어드리겠습니다

멘하임(BW)
진수하임(BW)
하일브론(BW)
문델스하임(BW)
슈투트가르트(BW)
글루이빙겐(BW)
울름(BW)

뷔르츠부르크(BY)
뉴른베르크(BY)
롤(BY)
안스바흐(BY)
그레이딩(BY)
잉골슈타트(BY)
크라일스하임(BY)

그리고 미션 선택지에서
바덴 뷔르탬베르크를 바덴 뷔르탬베르크(BW) 같은 식으로 표기하는것도 좋을듯 합니다
![1113](https://user-images.githubusercontent.com/23209374/71309877-765cd380-2450-11ea-9236-e66765beb718.png)

외국인 플레이 기준 도시 지도도 올려드립니다
수정하실때 참고하시면 될것 같습니다
![1112](https://user-images.githubusercontent.com/23209374/71309871-60e7a980-2450-11ea-909f-accc15bac622.png)

**Comment by morecool** [comment]
해당부분 수정 적용했습니다. 감사합니다.
