### ISSUE TITLE
캠페인 3-6 미션 : 거대도시 추가 설명 반영 요청

### ISSUE THREAD

**Issue by Twotoolus-FLY-LShst** [morecool/transportfever2_kr#25]
캠페인 3-6 미션 : 거대도시 추가 설명 반영 요청 입니다

아마 이것으로 이슈등록은 마지막일듯 싶습니다
캠페인 정주행 완료했고 더이상 추가적으로 필요한 번역 수정은 없을듯 합니다
(물론 부자연스러운 번역은 있겠지만 미션 진행하는데 지장은 되지 않습니다)

게임 버그인것인지
아니면 도시 키울라고 물자를 미리 다 배송해서인지
캠페인 3-6 미션 : 거대도시
보너스작업 > 상하이 TV탑
탑을 건설 미션에서 탑 위치가 어디인지 설명하는 문구가 없습니다

탑을 건설 설명란에
"건축에는 인력이 필요합니다."
밑에
상하이 중앙에 위치한 탑 건설장소로 인부를 배달합시다!

같은 문구를 추가시켜주셔서
상하이를 전혀 모르는 플레이어도 탑 건설미션에 지장이 없게 하는것이 어떨까 싶습니다

감사합니다
![123123](https://user-images.githubusercontent.com/23209374/71321424-68648c80-24fc-11ea-930f-c06f6cbca752.png)

**Comment by morecool** [comment]
해당 부분은 원래 영문판에도 없는 내용입니다만 저도 캠패인을 해보면서 일부 불친절한 부분이 있어 추가 설명이 있는게 좋다고 생각이 됩니다.

해당 부분 추가하여 반영하였습니다.
감사합니다.
